# Generated by Django 3.0.3 on 2020-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_test', models.CharField(max_length=200)),
                ('user_age', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=10)),
            ],
        ),
    ]
